# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: UTF-8
  host: localhost
  port: 5432
  database: 'hello_rails'
  username: 'postgres'
  password: 'postgres'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#database config pc optiplex

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  password: <%= ENV["ECOMMERCE_DATABASE_PASSWORD"] %>
